import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, {createContext, useState} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const UserDataContext = createContext();


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserDataContext.Provider value={{trancriptData, setTranscriptData}}>
          {children}
        </UserDataContext.Provider>
      </body>
    </html>
  );
}
